export const GET_POKEMONS_REQUEST = "GET_POKEMONS_REQUEST";
export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_POKEMONS_FAILURE = "GET_POKEMONS_FAILURE";

export const GET_POKEMON_BY_ID_REQUEST = "GET_POKEMON_BY_ID_REQUEST";
export const GET_POKEMON_BY_ID_SUCCESS = "GET_POKEMON_BY_ID_SUCCESS";
export const GET_POKEMON_BY_ID_FAILURE = "GET_POKEMON_BY_ID_FAILURE";

export const SEARCH_POKEMON_REQUEST = "SEARCH_POKEMON_REQUEST";
export const SEARCH_POKEMON_SUCCESS = "SEARCH_POKEMON_SUCCESS";
export const SEARCH_POKEMON_FAILURE = "SEARCH_POKEMON_FAILURE";

export const CREATE_POKEMON = "CREATE_POKEMON";
export const CREATE_POKEMON_SUCCESS = "CREATE_POKEMON_SUCCESS";
export const CREATE_POKEMON_FAILURE = "CREATE_POKEMON_FAILURE";

export const SET_POKEMONS = "SET_POKEMONS";
